In [162]:
import pandas as pd
import numpy as np

In [163]:
# Exercise 1
url = r"https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url)

df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'types']
df.index = [f"flower_{x+1}" for x in range(df.shape[0])]
df

,sepal_length,sepal_width,petal_length,petal_width,types
flower_1,4.9,3.0,1.4,0.2,Iris-setosa
flower_2,4.7,3.2,1.3,0.2,Iris-setosa
flower_3,4.6,3.1,1.5,0.2,Iris-setosa
flower_4,5.0,3.6,1.4,0.2,Iris-setosa
flower_5,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...
flower_145,6.7,3.0,5.2,2.3,Iris-virginica
flower_146,6.3,2.5,5.0,1.9,Iris-virginica
flower_147,6.5,3.0,5.2,2.0,Iris-virginica
flower_148,6.2,3.4,5.4,2.3,Iris-virginica
flower_149,5.9,3.0,5.1,1.8,Iris-virginica

In [164]:
# Exercise 2
df["types"].unique()

grouped_df = df.groupby("types")
grouped_df.mean()

df["sepal_width>3"] = df["sepal_width"] > 3

print(f"True values: {df.loc[df["sepal_width>3"] == True, "sepal_width>3"].count()}")
print(f"False values: {df.loc[df["sepal_width>3"] == False, "sepal_width>3"].count()}")

True values: 66
False values: 83

In [165]:
# Exercise 3

flower_df = []
for flower_breed in df["types"].unique():
    print(f"True values: {df.loc[df["types"] == flower_breed, "types"].count()}")
    flower_df.append(df.loc[df["types"] == flower_breed])

df.tail(10)

True values: 49
True values: 50
True values: 50

,sepal_length,sepal_width,petal_length,petal_width,types,sepal_width>3
flower_140,6.7,3.1,5.6,2.4,Iris-virginica,True
flower_141,6.9,3.1,5.1,2.3,Iris-virginica,True
flower_142,5.8,2.7,5.1,1.9,Iris-virginica,False
flower_143,6.8,3.2,5.9,2.3,Iris-virginica,True
flower_144,6.7,3.3,5.7,2.5,Iris-virginica,True
flower_145,6.7,3.0,5.2,2.3,Iris-virginica,False
flower_146,6.3,2.5,5.0,1.9,Iris-virginica,False
flower_147,6.5,3.0,5.2,2.0,Iris-virginica,False
flower_148,6.2,3.4,5.4,2.3,Iris-virginica,True
flower_149,5.9,3.0,5.1,1.8,Iris-virginica,False

In [166]:
# Exercise 4

def computation(x: float):
    if isinstance(x, str) == True:
        return x
    else:
        return (x+1)*3

df.loc[(df["sepal_length"] > 5) & (df["petal_width"] < 0.2)]
petal_width_df = df.loc[df["petal_width"] == 1.8]

df = df.drop("flower_55")
df = df.drop("flower_77")
df = df.drop("sepal_width>3", axis=1)
df.loc[df["petal_width"] == 1.8]
df.map(computation)


# df.loc["flower_55"]
# df.loc["flower_77"]

,sepal_length,sepal_width,petal_length,petal_width,types
flower_1,17.7,12.0,7.2,3.6,Iris-setosa
flower_2,17.1,12.6,6.9,3.6,Iris-setosa
flower_3,16.8,12.3,7.5,3.6,Iris-setosa
flower_4,18.0,13.8,7.2,3.6,Iris-setosa
flower_5,19.2,14.7,8.1,4.2,Iris-setosa
...,...,...,...,...,...
flower_145,23.1,12.0,18.6,9.9,Iris-virginica
flower_146,21.9,10.5,18.0,8.7,Iris-virginica
flower_147,22.5,12.0,18.6,9.0,Iris-virginica
flower_148,21.6,13.2,19.2,9.9,Iris-virginica
flower_149,20.7,12.0,18.3,8.4,Iris-virginica